# Generated by Django 4.1.3 on 2022-12-28 18:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0002_favorites'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='UserFavorites',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='favorite_by',
            field=models.ManyToManyField(related_name='favorite_advertisement', through='advertisements.UserFavorites', to=settings.AUTH_USER_MODEL),
        ),
    ]
